#!/bin/sh
mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t devtmpfs dev /dev
# lê role do cmdline do kernel
ROLE=$(grep -oE 'role=[a-z]+' /proc/cmdline | cut -d= -f2)
case "$ROLE" in
    rsu)     exec /rsu eth0 60 ;;
    *)       exec /vehicle eth0 30 ;;
esac