#!/bin/sh
#mkdir /sys /proc
#mount -t sysfs none /sys
#mount -t devtmpfs none /dev
#mount -t proc proc /proc
#ip link set eth0 up
#mount -t proc proc /proc
#setsid cttyhack sh

#!/bin/sh
mkdir /sys /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev
mount -t proc proc /proc
ip link set eth0 up

# lê os argumentos passados pelo kernel
CMDLINE=$(cat /proc/cmdline)
MODE=$(echo $CMDLINE | grep -o 'mode=[^ ]*' | cut -d= -f2)

# se não tiver modo definido, usa normal
if [ -z "$MODE" ]; then
    MODE="normal"
fi

./vehicle eth0 $MODE